spring.application.name=gemini-chat
gemini.api.url=${GEMINI_API_URL}
gemini.api.key=${GEMINI_API_KEY}
#gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-flash-latest:generateContent
#gemini.api.key=
